# Generated by Django 5.0.7 on 2025-10-19 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_product_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='colors',
            field=models.CharField(blank=True, help_text='ใส่หลายสีคั่นด้วย ,', max_length=255),
        ),
    ]
