# Generated by Django 5.0.7 on 2025-11-04 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0005_product_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='actual_received',
            field=models.DecimalField(decimal_places=2, default=0, help_text='จำนวนเงินที่ได้รับจริงหลังหักค่าคอมมิชชั่น', max_digits=10),
        ),
    ]
