# Generated by Django 5.0.7 on 2025-11-04 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0006_sale_actual_received'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='discount_percent',
            field=models.DecimalField(decimal_places=2, default=0, help_text='ส่วนลดเป็นเปอร์เซ็นต์จากราคาปกติ', max_digits=5),
        ),
    ]
