# Generated by Django 5.0.7 on 2025-12-22 11:28

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0008_sale_deleted_at_sale_is_deleted_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='รายการ')),
                ('category', models.CharField(choices=[('rent', 'ค่าเช่าที่'), ('utilities', 'ค่าน้ำ/ค่าไฟ'), ('salary', 'เงินเดือนพนักงาน'), ('marketing', 'การตลาด/โฆษณา'), ('restock', 'ซื้อสินค้าเติมสต็อก'), ('packaging', 'อุปกรณ์แพ็คของ'), ('transport', 'ค่าขนส่ง'), ('other', 'อื่นๆ')], default='other', max_length=50, verbose_name='หมวดหมู่')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='จำนวนเงิน')),
                ('paid_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='วันที่จ่าย')),
                ('note', models.TextField(blank=True, null=True, verbose_name='หมายเหตุ')),
                ('receipt_image', models.ImageField(blank=True, null=True, upload_to='expenses/', verbose_name='รูปสลิป/ใบเสร็จ')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name='sale',
            name='sold_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddIndex(
            model_name='sale',
            index=models.Index(fields=['sold_at'], name='sales_sale_sold_at_607748_idx'),
        ),
        migrations.AddIndex(
            model_name='sale',
            index=models.Index(fields=['is_deleted'], name='sales_sale_is_dele_e6e204_idx'),
        ),
    ]
