# Generated by Django 5.0.7 on 2025-12-22 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0009_expense_alter_sale_sold_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='เวลาที่ลบ'),
        ),
        migrations.AddField(
            model_name='expense',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='ลบแล้ว'),
        ),
    ]
