# Generated by Django 5.0.7 on 2026-01-18 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0010_expense_deleted_at_expense_is_deleted'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='ชื่อกลุ่ม')),
                ('description', models.TextField(blank=True, verbose_name='รายละเอียด')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('expenses', models.ManyToManyField(blank=True, related_name='report_groups', to='sales.expense', verbose_name='รายจ่าย')),
                ('sales', models.ManyToManyField(blank=True, related_name='report_groups', to='sales.sale', verbose_name='ยอดขาย')),
            ],
            options={
                'verbose_name': 'Report Group',
                'verbose_name_plural': 'Report Groups',
                'ordering': ['-created_at'],
            },
        ),
    ]
