# Generated by Django 5.0.7 on 2026-02-06 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0011_reportgroup'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='order_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Order ID'),
        ),
    ]
